version: '3'
services:
  app:
    container_name: Gateway_API
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - gateway-network

  db:
    container_name: Database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Saline
    ports:
      - "3306:3306"
    networks:
      - gateway-network
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: Database_Admin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge

volumes:
  db-data:
