version: '3'

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    expose:
      - "${APP_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - common-network

  db:
    container_name: Database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - common-network
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: Database_Admin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${ADMIN_PORT1}:${ADMIN_PORT2}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - common-network

networks:
  common-network:
    external:
      name: common-network

volumes:
  db-data:
