name: Déploiement vers VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Installation des dépendances SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: Connexion au VPS et déploiement
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ~/prod_server/orc && git pull origin main && docker-compose down && docker-compose up -d"
