name: Déploiement vers VPS

on:
  push:
    branches:
      - pre-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Installation des dépendances SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: Connexion au VPS et déploiement
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -p ${{secrets.VPS_PORT}} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ~/test/Gateway-Orchestrator && git pull origin pre-prod && docker-compose down && docker-compose up -d"
