name: Déploiement vers VPS

on:
  push:
    branches:
      - pre-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Installation des dépendances SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: Connexion au VPS et déploiement
      run: |
        ping ${{ secrets.VPS_HOST }}
